//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Sources/Services/Input/InputActionsSheme.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Assets.Sources.Services.Input
{
    public partial class @InputActionsSheme: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActionsSheme()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionsSheme"",
    ""maps"": [
        {
            ""name"": ""GameplayInput"",
            ""id"": ""fdde530e-b972-49b9-83b5-a918106ee15e"",
            ""actions"": [
                {
                    ""name"": ""HandlePressedMove"",
                    ""type"": ""Value"",
                    ""id"": ""9a464921-041a-40bd-84e8-04316e79395b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HandleMove"",
                    ""type"": ""Value"",
                    ""id"": ""7945845f-6bc8-4dc2-9377-fad9ec129c5d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press"",
                    ""type"": ""Value"",
                    ""id"": ""f0b0b76c-cde2-499f-8de8-1a59a27838df"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""f78891ff-2cd0-42c4-a1b8-aa0b8fca32eb"",
                    ""path"": ""OneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4c9f7686-c714-4cc0-8361-ae7b2e50d926"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""b7e3a017-08a5-43ad-a566-39a197db1db4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5138a63f-e945-40c7-8290-f3d252e660cf"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f606eea-1ba4-423f-a11a-5ca287c5a47f"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""08245fd8-d89d-4d88-b20f-1190ea8bb3a9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9cbf0a8f-3e06-41ba-98b3-a0df25f0af76"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ce8b8914-5eb4-4483-86c9-c6e287ad08fc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""36191520-911e-4fc6-92e0-fb4540b4d448"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""507c35c2-8023-4095-af46-b11f637d035d"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0fcfa9e0-cd55-445c-a541-556b69768406"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""683d4a70-3e03-4dc7-a413-c0460af5f6b1"",
                    ""path"": ""OneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f17317a8-b05f-458e-8ecb-131c42310c7a"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""10ddf3f8-2ab2-4acf-a521-5ece9e989d49"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""GameplayWindowInput"",
            ""id"": ""74df02b6-d5d6-409a-b9b2-1acdbf7f4155"",
            ""actions"": [
                {
                    ""name"": ""UndoButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""94887cc2-64aa-4951-914e-8d0a283f3301"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RemoveBuildingButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""dd8cc7a5-5049-42ab-9cc2-5b2dcf306e5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ReplaceBuildingButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""df085374-e02b-4a7b-8203-3e68caa7ea7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b6237c84-4f2b-4dca-ae21-3e9a67a57033"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UndoButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be247254-0c51-43e8-96ff-92465681d723"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RemoveBuildingButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76223388-43cc-4041-a3da-2592ac1b396e"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ReplaceBuildingButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SandboxWindowInput"",
            ""id"": ""a3eccc49-23a5-4c1b-bd30-fba95e5c94a6"",
            ""actions"": [
                {
                    ""name"": ""ClearTilesButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""582fc540-fe2b-46a2-a544-e0af43c4fd1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BuildingsButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""a0a7fd50-ac20-4a90-8fe8-f747973e3ab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GroundsButtonPressed"",
                    ""type"": ""Button"",
                    ""id"": ""04205c1e-16d2-41f3-a863-43c150237a5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8f96946d-062a-45f3-9ed5-a9058661c640"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearTilesButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb0fc95f-1f2e-4797-aeed-4d3ad981553a"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BuildingsButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07c9c47a-d68e-42e0-8d83-6cc9da8732d2"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GroundsButtonPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SandboxInput"",
            ""id"": ""7b6d7e48-ddb8-4f6a-afff-7ab58ad3e8b7"",
            ""actions"": [
                {
                    ""name"": ""FirstTouch"",
                    ""type"": ""Value"",
                    ""id"": ""00e10591-2ee4-4906-b801-5ceabf5fb22b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondTouch"",
                    ""type"": ""Value"",
                    ""id"": ""a34a6296-a9d5-455c-b323-061be04d71e1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MouseScroll"",
                    ""type"": ""Value"",
                    ""id"": ""20fecaeb-944d-4356-b46a-c6f10ebcb788"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateWorld"",
                    ""type"": ""Value"",
                    ""id"": ""50fdd226-ec3f-4bad-9397-de408fce685c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e81349c8-8967-4e26-b5af-6fb258a84191"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FirstTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""268c6f60-8880-4a09-b1f9-433a9fb18221"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bef466e-3db8-416c-9a46-325a89b2a675"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseScroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""df231783-a58e-4a8e-816f-0be76756e59b"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateWorld"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4c981bbe-df19-4789-bda8-2ec1e4769a04"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateWorld"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5df69bcb-3021-424d-b314-af0b1f5c882e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateWorld"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""48752b78-8a2f-42bd-ba0b-96cd23f028c3"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateWorld"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""70a69ae4-c640-42f0-8be6-46e13aaa3898"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateWorld"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""8c732685-922f-4b60-a609-72862c914d19"",
                    ""path"": ""<Touchscreen>/touch1/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateWorld"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // GameplayInput
            m_GameplayInput = asset.FindActionMap("GameplayInput", throwIfNotFound: true);
            m_GameplayInput_HandlePressedMove = m_GameplayInput.FindAction("HandlePressedMove", throwIfNotFound: true);
            m_GameplayInput_HandleMove = m_GameplayInput.FindAction("HandleMove", throwIfNotFound: true);
            m_GameplayInput_Press = m_GameplayInput.FindAction("Press", throwIfNotFound: true);
            // GameplayWindowInput
            m_GameplayWindowInput = asset.FindActionMap("GameplayWindowInput", throwIfNotFound: true);
            m_GameplayWindowInput_UndoButtonPressed = m_GameplayWindowInput.FindAction("UndoButtonPressed", throwIfNotFound: true);
            m_GameplayWindowInput_RemoveBuildingButtonPressed = m_GameplayWindowInput.FindAction("RemoveBuildingButtonPressed", throwIfNotFound: true);
            m_GameplayWindowInput_ReplaceBuildingButtonPressed = m_GameplayWindowInput.FindAction("ReplaceBuildingButtonPressed", throwIfNotFound: true);
            // SandboxWindowInput
            m_SandboxWindowInput = asset.FindActionMap("SandboxWindowInput", throwIfNotFound: true);
            m_SandboxWindowInput_ClearTilesButtonPressed = m_SandboxWindowInput.FindAction("ClearTilesButtonPressed", throwIfNotFound: true);
            m_SandboxWindowInput_BuildingsButtonPressed = m_SandboxWindowInput.FindAction("BuildingsButtonPressed", throwIfNotFound: true);
            m_SandboxWindowInput_GroundsButtonPressed = m_SandboxWindowInput.FindAction("GroundsButtonPressed", throwIfNotFound: true);
            // SandboxInput
            m_SandboxInput = asset.FindActionMap("SandboxInput", throwIfNotFound: true);
            m_SandboxInput_FirstTouch = m_SandboxInput.FindAction("FirstTouch", throwIfNotFound: true);
            m_SandboxInput_SecondTouch = m_SandboxInput.FindAction("SecondTouch", throwIfNotFound: true);
            m_SandboxInput_MouseScroll = m_SandboxInput.FindAction("MouseScroll", throwIfNotFound: true);
            m_SandboxInput_RotateWorld = m_SandboxInput.FindAction("RotateWorld", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GameplayInput
        private readonly InputActionMap m_GameplayInput;
        private List<IGameplayInputActions> m_GameplayInputActionsCallbackInterfaces = new List<IGameplayInputActions>();
        private readonly InputAction m_GameplayInput_HandlePressedMove;
        private readonly InputAction m_GameplayInput_HandleMove;
        private readonly InputAction m_GameplayInput_Press;
        public struct GameplayInputActions
        {
            private @InputActionsSheme m_Wrapper;
            public GameplayInputActions(@InputActionsSheme wrapper) { m_Wrapper = wrapper; }
            public InputAction @HandlePressedMove => m_Wrapper.m_GameplayInput_HandlePressedMove;
            public InputAction @HandleMove => m_Wrapper.m_GameplayInput_HandleMove;
            public InputAction @Press => m_Wrapper.m_GameplayInput_Press;
            public InputActionMap Get() { return m_Wrapper.m_GameplayInput; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayInputActions set) { return set.Get(); }
            public void AddCallbacks(IGameplayInputActions instance)
            {
                if (instance == null || m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Add(instance);
                @HandlePressedMove.started += instance.OnHandlePressedMove;
                @HandlePressedMove.performed += instance.OnHandlePressedMove;
                @HandlePressedMove.canceled += instance.OnHandlePressedMove;
                @HandleMove.started += instance.OnHandleMove;
                @HandleMove.performed += instance.OnHandleMove;
                @HandleMove.canceled += instance.OnHandleMove;
                @Press.started += instance.OnPress;
                @Press.performed += instance.OnPress;
                @Press.canceled += instance.OnPress;
            }

            private void UnregisterCallbacks(IGameplayInputActions instance)
            {
                @HandlePressedMove.started -= instance.OnHandlePressedMove;
                @HandlePressedMove.performed -= instance.OnHandlePressedMove;
                @HandlePressedMove.canceled -= instance.OnHandlePressedMove;
                @HandleMove.started -= instance.OnHandleMove;
                @HandleMove.performed -= instance.OnHandleMove;
                @HandleMove.canceled -= instance.OnHandleMove;
                @Press.started -= instance.OnPress;
                @Press.performed -= instance.OnPress;
                @Press.canceled -= instance.OnPress;
            }

            public void RemoveCallbacks(IGameplayInputActions instance)
            {
                if (m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGameplayInputActions instance)
            {
                foreach (var item in m_Wrapper.m_GameplayInputActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GameplayInputActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GameplayInputActions @GameplayInput => new GameplayInputActions(this);

        // GameplayWindowInput
        private readonly InputActionMap m_GameplayWindowInput;
        private List<IGameplayWindowInputActions> m_GameplayWindowInputActionsCallbackInterfaces = new List<IGameplayWindowInputActions>();
        private readonly InputAction m_GameplayWindowInput_UndoButtonPressed;
        private readonly InputAction m_GameplayWindowInput_RemoveBuildingButtonPressed;
        private readonly InputAction m_GameplayWindowInput_ReplaceBuildingButtonPressed;
        public struct GameplayWindowInputActions
        {
            private @InputActionsSheme m_Wrapper;
            public GameplayWindowInputActions(@InputActionsSheme wrapper) { m_Wrapper = wrapper; }
            public InputAction @UndoButtonPressed => m_Wrapper.m_GameplayWindowInput_UndoButtonPressed;
            public InputAction @RemoveBuildingButtonPressed => m_Wrapper.m_GameplayWindowInput_RemoveBuildingButtonPressed;
            public InputAction @ReplaceBuildingButtonPressed => m_Wrapper.m_GameplayWindowInput_ReplaceBuildingButtonPressed;
            public InputActionMap Get() { return m_Wrapper.m_GameplayWindowInput; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameplayWindowInputActions set) { return set.Get(); }
            public void AddCallbacks(IGameplayWindowInputActions instance)
            {
                if (instance == null || m_Wrapper.m_GameplayWindowInputActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GameplayWindowInputActionsCallbackInterfaces.Add(instance);
                @UndoButtonPressed.started += instance.OnUndoButtonPressed;
                @UndoButtonPressed.performed += instance.OnUndoButtonPressed;
                @UndoButtonPressed.canceled += instance.OnUndoButtonPressed;
                @RemoveBuildingButtonPressed.started += instance.OnRemoveBuildingButtonPressed;
                @RemoveBuildingButtonPressed.performed += instance.OnRemoveBuildingButtonPressed;
                @RemoveBuildingButtonPressed.canceled += instance.OnRemoveBuildingButtonPressed;
                @ReplaceBuildingButtonPressed.started += instance.OnReplaceBuildingButtonPressed;
                @ReplaceBuildingButtonPressed.performed += instance.OnReplaceBuildingButtonPressed;
                @ReplaceBuildingButtonPressed.canceled += instance.OnReplaceBuildingButtonPressed;
            }

            private void UnregisterCallbacks(IGameplayWindowInputActions instance)
            {
                @UndoButtonPressed.started -= instance.OnUndoButtonPressed;
                @UndoButtonPressed.performed -= instance.OnUndoButtonPressed;
                @UndoButtonPressed.canceled -= instance.OnUndoButtonPressed;
                @RemoveBuildingButtonPressed.started -= instance.OnRemoveBuildingButtonPressed;
                @RemoveBuildingButtonPressed.performed -= instance.OnRemoveBuildingButtonPressed;
                @RemoveBuildingButtonPressed.canceled -= instance.OnRemoveBuildingButtonPressed;
                @ReplaceBuildingButtonPressed.started -= instance.OnReplaceBuildingButtonPressed;
                @ReplaceBuildingButtonPressed.performed -= instance.OnReplaceBuildingButtonPressed;
                @ReplaceBuildingButtonPressed.canceled -= instance.OnReplaceBuildingButtonPressed;
            }

            public void RemoveCallbacks(IGameplayWindowInputActions instance)
            {
                if (m_Wrapper.m_GameplayWindowInputActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGameplayWindowInputActions instance)
            {
                foreach (var item in m_Wrapper.m_GameplayWindowInputActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GameplayWindowInputActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GameplayWindowInputActions @GameplayWindowInput => new GameplayWindowInputActions(this);

        // SandboxWindowInput
        private readonly InputActionMap m_SandboxWindowInput;
        private List<ISandboxWindowInputActions> m_SandboxWindowInputActionsCallbackInterfaces = new List<ISandboxWindowInputActions>();
        private readonly InputAction m_SandboxWindowInput_ClearTilesButtonPressed;
        private readonly InputAction m_SandboxWindowInput_BuildingsButtonPressed;
        private readonly InputAction m_SandboxWindowInput_GroundsButtonPressed;
        public struct SandboxWindowInputActions
        {
            private @InputActionsSheme m_Wrapper;
            public SandboxWindowInputActions(@InputActionsSheme wrapper) { m_Wrapper = wrapper; }
            public InputAction @ClearTilesButtonPressed => m_Wrapper.m_SandboxWindowInput_ClearTilesButtonPressed;
            public InputAction @BuildingsButtonPressed => m_Wrapper.m_SandboxWindowInput_BuildingsButtonPressed;
            public InputAction @GroundsButtonPressed => m_Wrapper.m_SandboxWindowInput_GroundsButtonPressed;
            public InputActionMap Get() { return m_Wrapper.m_SandboxWindowInput; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SandboxWindowInputActions set) { return set.Get(); }
            public void AddCallbacks(ISandboxWindowInputActions instance)
            {
                if (instance == null || m_Wrapper.m_SandboxWindowInputActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SandboxWindowInputActionsCallbackInterfaces.Add(instance);
                @ClearTilesButtonPressed.started += instance.OnClearTilesButtonPressed;
                @ClearTilesButtonPressed.performed += instance.OnClearTilesButtonPressed;
                @ClearTilesButtonPressed.canceled += instance.OnClearTilesButtonPressed;
                @BuildingsButtonPressed.started += instance.OnBuildingsButtonPressed;
                @BuildingsButtonPressed.performed += instance.OnBuildingsButtonPressed;
                @BuildingsButtonPressed.canceled += instance.OnBuildingsButtonPressed;
                @GroundsButtonPressed.started += instance.OnGroundsButtonPressed;
                @GroundsButtonPressed.performed += instance.OnGroundsButtonPressed;
                @GroundsButtonPressed.canceled += instance.OnGroundsButtonPressed;
            }

            private void UnregisterCallbacks(ISandboxWindowInputActions instance)
            {
                @ClearTilesButtonPressed.started -= instance.OnClearTilesButtonPressed;
                @ClearTilesButtonPressed.performed -= instance.OnClearTilesButtonPressed;
                @ClearTilesButtonPressed.canceled -= instance.OnClearTilesButtonPressed;
                @BuildingsButtonPressed.started -= instance.OnBuildingsButtonPressed;
                @BuildingsButtonPressed.performed -= instance.OnBuildingsButtonPressed;
                @BuildingsButtonPressed.canceled -= instance.OnBuildingsButtonPressed;
                @GroundsButtonPressed.started -= instance.OnGroundsButtonPressed;
                @GroundsButtonPressed.performed -= instance.OnGroundsButtonPressed;
                @GroundsButtonPressed.canceled -= instance.OnGroundsButtonPressed;
            }

            public void RemoveCallbacks(ISandboxWindowInputActions instance)
            {
                if (m_Wrapper.m_SandboxWindowInputActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ISandboxWindowInputActions instance)
            {
                foreach (var item in m_Wrapper.m_SandboxWindowInputActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SandboxWindowInputActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public SandboxWindowInputActions @SandboxWindowInput => new SandboxWindowInputActions(this);

        // SandboxInput
        private readonly InputActionMap m_SandboxInput;
        private List<ISandboxInputActions> m_SandboxInputActionsCallbackInterfaces = new List<ISandboxInputActions>();
        private readonly InputAction m_SandboxInput_FirstTouch;
        private readonly InputAction m_SandboxInput_SecondTouch;
        private readonly InputAction m_SandboxInput_MouseScroll;
        private readonly InputAction m_SandboxInput_RotateWorld;
        public struct SandboxInputActions
        {
            private @InputActionsSheme m_Wrapper;
            public SandboxInputActions(@InputActionsSheme wrapper) { m_Wrapper = wrapper; }
            public InputAction @FirstTouch => m_Wrapper.m_SandboxInput_FirstTouch;
            public InputAction @SecondTouch => m_Wrapper.m_SandboxInput_SecondTouch;
            public InputAction @MouseScroll => m_Wrapper.m_SandboxInput_MouseScroll;
            public InputAction @RotateWorld => m_Wrapper.m_SandboxInput_RotateWorld;
            public InputActionMap Get() { return m_Wrapper.m_SandboxInput; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SandboxInputActions set) { return set.Get(); }
            public void AddCallbacks(ISandboxInputActions instance)
            {
                if (instance == null || m_Wrapper.m_SandboxInputActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SandboxInputActionsCallbackInterfaces.Add(instance);
                @FirstTouch.started += instance.OnFirstTouch;
                @FirstTouch.performed += instance.OnFirstTouch;
                @FirstTouch.canceled += instance.OnFirstTouch;
                @SecondTouch.started += instance.OnSecondTouch;
                @SecondTouch.performed += instance.OnSecondTouch;
                @SecondTouch.canceled += instance.OnSecondTouch;
                @MouseScroll.started += instance.OnMouseScroll;
                @MouseScroll.performed += instance.OnMouseScroll;
                @MouseScroll.canceled += instance.OnMouseScroll;
                @RotateWorld.started += instance.OnRotateWorld;
                @RotateWorld.performed += instance.OnRotateWorld;
                @RotateWorld.canceled += instance.OnRotateWorld;
            }

            private void UnregisterCallbacks(ISandboxInputActions instance)
            {
                @FirstTouch.started -= instance.OnFirstTouch;
                @FirstTouch.performed -= instance.OnFirstTouch;
                @FirstTouch.canceled -= instance.OnFirstTouch;
                @SecondTouch.started -= instance.OnSecondTouch;
                @SecondTouch.performed -= instance.OnSecondTouch;
                @SecondTouch.canceled -= instance.OnSecondTouch;
                @MouseScroll.started -= instance.OnMouseScroll;
                @MouseScroll.performed -= instance.OnMouseScroll;
                @MouseScroll.canceled -= instance.OnMouseScroll;
                @RotateWorld.started -= instance.OnRotateWorld;
                @RotateWorld.performed -= instance.OnRotateWorld;
                @RotateWorld.canceled -= instance.OnRotateWorld;
            }

            public void RemoveCallbacks(ISandboxInputActions instance)
            {
                if (m_Wrapper.m_SandboxInputActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ISandboxInputActions instance)
            {
                foreach (var item in m_Wrapper.m_SandboxInputActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SandboxInputActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public SandboxInputActions @SandboxInput => new SandboxInputActions(this);
        public interface IGameplayInputActions
        {
            void OnHandlePressedMove(InputAction.CallbackContext context);
            void OnHandleMove(InputAction.CallbackContext context);
            void OnPress(InputAction.CallbackContext context);
        }
        public interface IGameplayWindowInputActions
        {
            void OnUndoButtonPressed(InputAction.CallbackContext context);
            void OnRemoveBuildingButtonPressed(InputAction.CallbackContext context);
            void OnReplaceBuildingButtonPressed(InputAction.CallbackContext context);
        }
        public interface ISandboxWindowInputActions
        {
            void OnClearTilesButtonPressed(InputAction.CallbackContext context);
            void OnBuildingsButtonPressed(InputAction.CallbackContext context);
            void OnGroundsButtonPressed(InputAction.CallbackContext context);
        }
        public interface ISandboxInputActions
        {
            void OnFirstTouch(InputAction.CallbackContext context);
            void OnSecondTouch(InputAction.CallbackContext context);
            void OnMouseScroll(InputAction.CallbackContext context);
            void OnRotateWorld(InputAction.CallbackContext context);
        }
    }
}
