//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Sources/Services/Input/InputActionsSheme.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Assets.Sources.Services.Input
{
    public partial class @InputActionsSheme: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActionsSheme()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionsSheme"",
    ""maps"": [
        {
            ""name"": ""Input"",
            ""id"": ""fdde530e-b972-49b9-83b5-a918106ee15e"",
            ""actions"": [
                {
                    ""name"": ""HandlePressedMove"",
                    ""type"": ""Value"",
                    ""id"": ""9a464921-041a-40bd-84e8-04316e79395b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""HandleMove"",
                    ""type"": ""Value"",
                    ""id"": ""7945845f-6bc8-4dc2-9377-fad9ec129c5d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press"",
                    ""type"": ""Value"",
                    ""id"": ""f0b0b76c-cde2-499f-8de8-1a59a27838df"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""f78891ff-2cd0-42c4-a1b8-aa0b8fca32eb"",
                    ""path"": ""OneModifier"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""4c9f7686-c714-4cc0-8361-ae7b2e50d926"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Binding"",
                    ""id"": ""b7e3a017-08a5-43ad-a566-39a197db1db4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandlePressedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5138a63f-e945-40c7-8290-f3d252e660cf"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandleMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""08245fd8-d89d-4d88-b20f-1190ea8bb3a9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""9cbf0a8f-3e06-41ba-98b3-a0df25f0af76"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""ce8b8914-5eb4-4483-86c9-c6e287ad08fc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Input
            m_Input = asset.FindActionMap("Input", throwIfNotFound: true);
            m_Input_HandlePressedMove = m_Input.FindAction("HandlePressedMove", throwIfNotFound: true);
            m_Input_HandleMove = m_Input.FindAction("HandleMove", throwIfNotFound: true);
            m_Input_Press = m_Input.FindAction("Press", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Input
        private readonly InputActionMap m_Input;
        private List<IInputActions> m_InputActionsCallbackInterfaces = new List<IInputActions>();
        private readonly InputAction m_Input_HandlePressedMove;
        private readonly InputAction m_Input_HandleMove;
        private readonly InputAction m_Input_Press;
        public struct InputActions
        {
            private @InputActionsSheme m_Wrapper;
            public InputActions(@InputActionsSheme wrapper) { m_Wrapper = wrapper; }
            public InputAction @HandlePressedMove => m_Wrapper.m_Input_HandlePressedMove;
            public InputAction @HandleMove => m_Wrapper.m_Input_HandleMove;
            public InputAction @Press => m_Wrapper.m_Input_Press;
            public InputActionMap Get() { return m_Wrapper.m_Input; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(InputActions set) { return set.Get(); }
            public void AddCallbacks(IInputActions instance)
            {
                if (instance == null || m_Wrapper.m_InputActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_InputActionsCallbackInterfaces.Add(instance);
                @HandlePressedMove.started += instance.OnHandlePressedMove;
                @HandlePressedMove.performed += instance.OnHandlePressedMove;
                @HandlePressedMove.canceled += instance.OnHandlePressedMove;
                @HandleMove.started += instance.OnHandleMove;
                @HandleMove.performed += instance.OnHandleMove;
                @HandleMove.canceled += instance.OnHandleMove;
                @Press.started += instance.OnPress;
                @Press.performed += instance.OnPress;
                @Press.canceled += instance.OnPress;
            }

            private void UnregisterCallbacks(IInputActions instance)
            {
                @HandlePressedMove.started -= instance.OnHandlePressedMove;
                @HandlePressedMove.performed -= instance.OnHandlePressedMove;
                @HandlePressedMove.canceled -= instance.OnHandlePressedMove;
                @HandleMove.started -= instance.OnHandleMove;
                @HandleMove.performed -= instance.OnHandleMove;
                @HandleMove.canceled -= instance.OnHandleMove;
                @Press.started -= instance.OnPress;
                @Press.performed -= instance.OnPress;
                @Press.canceled -= instance.OnPress;
            }

            public void RemoveCallbacks(IInputActions instance)
            {
                if (m_Wrapper.m_InputActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IInputActions instance)
            {
                foreach (var item in m_Wrapper.m_InputActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_InputActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public InputActions @Input => new InputActions(this);
        public interface IInputActions
        {
            void OnHandlePressedMove(InputAction.CallbackContext context);
            void OnHandleMove(InputAction.CallbackContext context);
            void OnPress(InputAction.CallbackContext context);
        }
    }
}
